on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-rust.yml@ba8e57aea2e8211b3c2c69f3ab218e73852e6d13 # v3.4.1
